import type { Metadata } from "next";
import "../globals.css";
import Nav from "../components/user/Nav";
// import Nav from "./(user-end)/components/Nav";
import Footer from "../components/user/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
